import {
	Plus,
	Car,
	Check,
	ClipboardList,
	LayoutPanelLeft,
	SquarePlus,
	EditIcon,
	Eye,
	EyeOff,
	Trash2,
	LoaderPinwheel,
	CloudUpload,
	List,
	TriangleAlert,
	Search,
	Users,
	Fuel,
	MapPin,
	Funnel,
	Calendar,
	CircleCheckBig,
	Moon,
	Sun,
	TextAlignEnd,
	X,
	CircleUser,
	ArrowRight,
	Star,
	ChevronLeft,
	ChevronRight,
	Instagram,
	Facebook,
	Twitter,
	Mail,
	CalendarX,
	Loader,
	ArrowLeft,
	MessageCircleMore,
	MousePointer2,
	ArrowDown,
	Send,
	Menu,
	Clock,
	CheckCheck,
	CheckCircle2,
	Sparkles,
	Wrench,
	CircleX,
	Wallet,
	CreditCard,
	IndianRupee,
	CalendarCheck,
	ClipboardCheck,
	MessageCircle,
	User,
	CarFront,
	Paperclip,
	Image,
	FileText,
	Download,
	Home
} from "lucide-react";

export const cityList = [
	"Jaipur",
	"Udaipur",
	"Kota",
	"Mumbai",
	"Delhi",
	"Gurugram",
];

export const iconList = {
	Plus,
	Check,
	EditIcon,
	Eye,
	EyeOff,
	Trash2,
	LoaderPinwheel,
	CloudUpload,
	TriangleAlert,
	List,
	Search,
	Users,
	Fuel,
	Car,
	MapPin,
	CalendarX,
	Funnel,
	Calendar,
	CircleCheckBig,
	Moon,
	Sun,
	TextAlignEnd,
	X,
	ClipboardList,
	CircleUser,
	ArrowRight,
	Star,
	ChevronLeft,
	ChevronRight,
	Instagram,
	Facebook,
	Twitter,
	Mail,
	Loader,
	ArrowLeft,
	MessageCircleMore,
	MousePointer2,
	ArrowDown,
	Send,
	Menu,
	Clock,
	CheckCheck,
	CheckCircle2,
	Sparkles,
	Wrench,
	CircleX,
	Wallet,
	CreditCard,
	IndianRupee,
	CalendarCheck,
	ClipboardCheck,
	MessageCircle,
	User,
	CarFront,
	Paperclip,
	Image,
	FileText,
	Download,
	Home
};

export const assets = {
	logo: "/svgs/logo.svg",
	main_car: "/main_car.png",
	banner_car_image: "/images/banner_car_image.png",
};

export const menuLinks = [
	{ name: "Home", path: "/" },
	{ name: "Cars", path: "/cars" },
	{ name: "My Bookings", path: "/my-bookings" },
	{ name: "Chat with owner", path: "/chatpage" },
];

export const ownerMenuLinks = [
	{ name: "Dashboard", path: "/owner", icon: <LayoutPanelLeft /> },
	{ name: "Add car", path: "/owner/add-car", icon: <SquarePlus /> },
	{ name: "Manage Cars", path: "/owner/manage-cars", icon: <Car /> },
	{
		name: "Manage Bookings",
		path: "/owner/manage-bookings",
		icon: <ClipboardList />,
	},
	{ name: "All Users", path: "/owner/users", icon: <Users /> },
	{ name: "Subscribers", path: "/owner/subscribers", icon: <Mail /> },
	{ name: "All Chats", path: "/owner/chats", icon: <MessageCircleMore /> }
];
